=== rall138/Pattern01/generalconfig/PatternSchemaDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="PatternDefinition" >
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Element" type="ElementType" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" default="WWPattern"/>
		</xs:complexType>
	</xs:element>
	
	<xs:complexType name="AttributeType">
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="required" use="required" type="xs:boolean"/>
		<xs:attribute name="type" use="required" type="xs:string"/>
		<xs:attribute name="group" use="optional" default="General" type="xs:string"/>
		<xs:attribute name="default" use="optional" type="xs:string"/>
		<xs:attribute name="userDescription" use="optional" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="ChildElementType">
		<xs:attribute name="references" type="xs:string" use="required"/>
		<xs:attribute name="unique" type="xs:boolean" use="required" />
	</xs:complexType>
	
	<xs:complexType name="ElementType" mixed="true">
		<xs:sequence>
			<xs:element name="AttributeElement" type="AttributeType" minOccurs="0" nillable="true" maxOccurs="unbounded" />
			<xs:element name="ChildElement" type="ChildElementType" minOccurs="0" nillable="true" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" use="required" type="xs:string"/>
		<xs:attribute name="default" use="optional" type="xs:string"/>
		<xs:attribute name="image" use="required" type="xs:anyURI"/>
		<xs:attribute name="unique" type="xs:boolean" use="optional" />
		<xs:attribute name="userDescription" use="optional" type="xs:string"/>
	</xs:complexType>
	
</xs:schema>

=== rall138/Pattern01/generalconfig/PatternDefinition.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE PatternDefinition PUBLIC "//UNKNOWN/" "PatternDefinition.dtd">
<PatternDefinition 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="PatternSchemaDefinition.xsd">

	<Element name="patternInstance" image="primefaces.jpg" unique="true" >
		<AttributeElement name="generator" type="#{Generator}" required="true" default="#{Generator.WEB}" />
		<AttributeElement name="name" type="java.lang.String" required="true" />
		<AttributeElement name="description" type="java.lang.String" required="false" />
		<ChildElement references="relatedFiles" unique="true" />
		<ChildElement references="faces" unique="true" />		
	</Element>
	
	<Element name="relatedFiles" unique="true" image="primefaces.jpg">
		<AttributeElement name="image" type="java.lang.String" required="true" default="primefaces.jpg" />		
		<ChildElement references="relatedFile" unique="false" />
	</Element>
	
	<Element name="relatedFile" image="primefaces.jpg"  unique="false">
		<AttributeElement name="name" type="java.lang.String" required="true" />
		<AttributeElement name="description" type="java.lang.String" required="false" />
		<AttributeElement name="reference" type="java.lang.String" required="true" />
	</Element>

	<Element name="faces" image="primefaces.jpg">
		<ChildElement references="selection" unique="true" />
		<ChildElement references="register" unique="true" />
		<ChildElement references="dialog" unique="false" />
	</Element>
	
	<Element name="selection" image="primefaces.jpg">
		<AttributeElement name="name" type="java.lang.String" required="true" />
		<AttributeElement name="description" type="java.lang.String" required="false" />
		<AttributeElement name="reference" type="java.lang.String" required="true" />
		<AttributeElement name="insert" type="#{Bool}" required="true" default="#{Bool.TRUE}" group="Mode"/>
		<AttributeElement name="update" type="#{Bool}" required="true" default="#{Bool.TRUE}" group="Mode"/>
		<AttributeElement name="delete" type="#{Bool}" required="true" default="#{Bool.TRUE}" group="Mode"/>
		<AttributeElement name="display" type="#{Bool}" required="true" default="#{Bool.TRUE}" group="Mode"/>
	</Element>
	
	<Element name="register" image="primefaces.jpg">
		<AttributeElement name="name" type="java.lang.String" required="true" />
		<AttributeElement name="description" type="java.lang.String" required="false" />
		<AttributeElement name="reference" type="java.lang.String" required="true" />
	</Element>
	
	<Element name="dialog" image="primefaces.jpg">
		<AttributeElement name="name" type="java.lang.String" required="true" />
		<AttributeElement name="description" type="java.lang.String" required="false" />
		<AttributeElement name="reference" type="java.lang.String" required="true" />
	</Element>
	
	<Element name="form" image="primefaces.jpg">
		<AttributeElement name="name" type="java.lang.String" required="false" />
	</Element>

	<Element name="table" image="primefaces.jpg">
		<AttributeElement name="name" type="java.lang.String" required="false" />
		<AttributeElement name="columns" type="java.lang.Integer" required="true" default="0" userDescription="Number of columns for distributing data" />
	</Element>

	<Element name="grid" image="primefaces.jpg">
		<AttributeElement name="name" type="java.lang.String" required="false" />
	</Element>
	
	<Element name="input" image="primefaces.jpg">
		<AttributeElement name="name" type="java.lang.String" required="false" />
		<AttributeElement name="readonly" type="java.lang.String" required="true" default="false" />
		<AttributeElement name="datatype" type="#{DataType}" required="true" default="#{DataType.ALPHANUMERIC}" />
		<AttributeElement name="datatype" type="#{DataType}" required="true" default="#{DataType.ALPHANUMERIC}" />
	</Element>
	
</PatternDefinition>
